from enum import StrEnum


class EntityType(StrEnum):
    COUNTRY = "country"
    CONVENIENCE_REGION = "convenience_region"
    PREFECTURE = "prefecture"
    HOKKAIDO_SUBPREFECTURE = "hokkaido_subprefecture"
    COUNTY_DISTRICT = "county_district"
    MUNICIPALITY = "municipality"
    TOKYO_SPECIAL_WARD = "tokyo_special_ward"
    DESIGNATED_CITY_WARD = "designated_city_ward"
    TOWN_AZA = "town_aza"
    ISLAND = "island"
    REMOTE_ISLAND_GROUPING = "remote_island_grouping"
    ADMINISTRATIVE_REFERENCE = "administrative_reference"


class CoverageState(StrEnum):
    DIRECT_ACTIVE = "DIRECT_ACTIVE"
    DIRECT_ZERO_INVENTORY = "DIRECT_ZERO_INVENTORY"
    DIRECT_REGISTRATION_REQUIRED = "DIRECT_REGISTRATION_REQUIRED"
    DIRECT_PAPER_ONLY = "DIRECT_PAPER_ONLY"
    DIRECT_DISCONTINUED = "DIRECT_DISCONTINUED"
    PREFECTURAL_ONLY = "PREFECTURAL_ONLY"
    REGIONAL_ONLY = "REGIONAL_ONLY"
    NATIONAL_BANK_ONLY = "NATIONAL_BANK_ONLY"
    PUBLIC_ASSET_ONLY = "PUBLIC_ASSET_ONLY"
    DISCOVERED_UNPARSED = "DISCOVERED_UNPARSED"
    SOURCE_BROKEN = "SOURCE_BROKEN"
    SOURCE_BLOCKED = "SOURCE_BLOCKED"
    SOURCE_MISSING = "SOURCE_MISSING"
    UNDER_REVIEW = "UNDER_REVIEW"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    ADMINISTRATIVE_REFERENCE_ONLY = "ADMINISTRATIVE_REFERENCE_ONLY"


class SourceClass(StrEnum):
    NATIONAL_GOVERNMENT = "NATIONAL_GOVERNMENT"
    NATIONWIDE_AKIYA_BANK = "NATIONWIDE_AKIYA_BANK"
    PREFECTURAL_REGIONAL = "PREFECTURAL_REGIONAL"
    MUNICIPAL_DIRECT = "MUNICIPAL_DIRECT"
    GENERAL_HOME_SEARCH = "GENERAL_HOME_SEARCH"
    PUBLIC_ASSET = "PUBLIC_ASSET"
    SUPPORTING_DATA = "SUPPORTING_DATA"


class AccessMode(StrEnum):
    PUBLIC_API = "PUBLIC_API"
    PUBLIC_JSON = "PUBLIC_JSON"
    PUBLIC_CSV = "PUBLIC_CSV"
    PUBLIC_XML = "PUBLIC_XML"
    PUBLIC_RSS = "PUBLIC_RSS"
    PUBLIC_HTML = "PUBLIC_HTML"
    PUBLIC_JAVASCRIPT_APP = "PUBLIC_JAVASCRIPT_APP"
    PUBLIC_PDF = "PUBLIC_PDF"
    PUBLIC_SPREADSHEET = "PUBLIC_SPREADSHEET"
    PUBLIC_IMAGE_DOCUMENT = "PUBLIC_IMAGE_DOCUMENT"
    MANUAL_IMPORT = "MANUAL_IMPORT"
    REGISTRATION_REQUIRED = "REGISTRATION_REQUIRED"
    PAPER_ONLY = "PAPER_ONLY"
    DISABLED = "DISABLED"


class SourceHealth(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    STALE = "STALE"
    PARSER_DRIFT = "PARSER_DRIFT"
    RATE_LIMITED = "RATE_LIMITED"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
    BLOCKED = "BLOCKED"
    DISABLED = "DISABLED"
    UNKNOWN = "UNKNOWN"


class ListingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    NEW = "NEW"
    AVAILABLE = "AVAILABLE"
    APPLICATION_OPEN = "APPLICATION_OPEN"
    UNDER_NEGOTIATION = "UNDER_NEGOTIATION"
    APPLICATION_PENDING = "APPLICATION_PENDING"
    RESERVED = "RESERVED"
    APPLICATION_CLOSED = "APPLICATION_CLOSED"
    SOLD = "SOLD"
    RENTED = "RENTED"
    TRANSFERRED = "TRANSFERRED"
    WITHDRAWN = "WITHDRAWN"
    EXPIRED = "EXPIRED"
    REMOVED_FROM_SOURCE = "REMOVED_FROM_SOURCE"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    STATUS_UNKNOWN = "STATUS_UNKNOWN"


class TransactionType(StrEnum):
    SALE = "sale"
    RENT = "rent"
    LEASE = "lease"
    RENT_TO_OWN = "rent_to_own"
    TRANSFER = "transfer"
    FREE_TRANSFER = "free_transfer"
    AUCTION = "auction"
    TENDER = "tender"
    TRIAL_RESIDENCE = "trial_residence"
    NEGOTIATION = "negotiation"
    UNKNOWN = "unknown"


class PriceKind(StrEnum):
    FIXED = "FIXED"
    NEGOTIABLE = "NEGOTIABLE"
    ZERO_PRICE = "ZERO_PRICE"
    FREE_TRANSFER = "FREE_TRANSFER"
    MINIMUM_BID = "MINIMUM_BID"
    RESERVE_PRICE = "RESERVE_PRICE"
    MONTHLY_RENT = "MONTHLY_RENT"
    ANNUAL_RENT = "ANNUAL_RENT"
    UNDISCLOSED = "UNDISCLOSED"
    PENDING = "PENDING"
    UNKNOWN = "UNKNOWN"


class PropertyType(StrEnum):
    DETACHED_HOUSE = "detached_house"
    ROW_HOUSE = "row_house"
    CONDOMINIUM = "condominium"
    APARTMENT_UNIT = "apartment_unit"
    APARTMENT_BUILDING = "apartment_building"
    KOMINKA = "kominka"
    FARMHOUSE = "farmhouse"
    HOUSE_WITH_FARMLAND = "house_with_farmland"
    MIXED_RESIDENTIAL_COMMERCIAL = "mixed_residential_commercial"
    SHOP_WITH_RESIDENCE = "shop_with_residence"
    VACANT_LAND = "vacant_land"
    RESIDENTIAL_LOT = "residential_lot"
    AGRICULTURAL_LAND = "agricultural_land"
    FOREST = "forest"
    WAREHOUSE = "warehouse"
    FACTORY = "factory"
    OFFICE = "office"
    LODGING = "lodging"
    PUBLIC_BUILDING = "public_building"
    FORMER_SCHOOL = "former_school"
    TRIAL_RESIDENCE = "trial_residence"
    OTHER = "other"
    UNKNOWN = "unknown"


class LocationPrecision(StrEnum):
    EXACT_BUILDING = "EXACT_BUILDING"
    EXACT_PARCEL = "EXACT_PARCEL"
    STREET_BLOCK = "STREET_BLOCK"
    TOWN_AZA = "TOWN_AZA"
    POSTCODE = "POSTCODE"
    MUNICIPALITY = "MUNICIPALITY"
    PREFECTURE = "PREFECTURE"
    SOURCE_MAP_ONLY = "SOURCE_MAP_ONLY"
    WITHHELD = "WITHHELD"
    UNKNOWN = "UNKNOWN"


class TranslationState(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    MACHINE_TRANSLATED = "MACHINE_TRANSLATED"
    MACHINE_TRANSLATION_REVIEWED = "MACHINE_TRANSLATION_REVIEWED"
    HUMAN_REVIEWED = "HUMAN_REVIEWED"
    FAILED = "FAILED"
    STALE_AFTER_SOURCE_CHANGE = "STALE_AFTER_SOURCE_CHANGE"


class ConditionCategory(StrEnum):
    IMMEDIATELY_HABITABLE = "immediately_habitable"
    MINOR_REPAIR = "minor_repair"
    SUBSTANTIAL_REPAIR = "substantial_repair"
    MAJOR_REHABILITATION = "major_rehabilitation"
    DEMOLITION_REQUIRED = "demolition_required"
    STRUCTURE_ONLY = "structure_only"
    NOT_INSPECTED = "not_inspected"
    UNKNOWN = "unknown"
